language: ruby
script:
  - bundle exec rspec spec
  - bundle exec cucumber --no-profile --color --format progress --strict --tags ~@really_long_process
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
matrix:
  include:
  - rvm: jruby-18mode
    jdk: openjdk7
  - rvm: jruby-19mode
    jdk: openjdk7

  allow_failures:
  - rvm: jruby-18mode
  - rvm: jruby-19mode
  - rvm: rbx-18mode
  - rvm: rbx-19mode
