language: ruby
script: SKIP_SIMPLECOV=true bundle exec rspec spec
after_script: bundle exec cucumber --no-profile --color --format progress --strict
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - rbx
